### ISSUE TITLE
Normalize repository

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl#106]
Like all the others.

**Comment by phated** [comment]
I believe this is almost wrapped up.

@terinjokes @contra @darsain can you review my README changes at https://github.com/gulpjs/vinyl/blob/repo-normalization/README.md

**Comment by darsain** [comment]
Viny => Vinyl typo in this title here: https://github.com/gulpjs/vinyl/blob/repo-normalization/README.md#vinyisvinylfile

Apart of that didn't catch anything else 👍
