### ISSUE TITLE
What about delete ?

### ISSUE THREAD

**Issue by mmc41** [gulpjs/vinyl#126]
I am looking for a js virtual file system where I can read/create/update/delete "files" and "folders" of various kinds.

Vinyl looks great but it seems vinyl can only do 3/4 of filesystem operations, since I could find no way to delete virtual files in a portable manner that works across adapters. Is that correct or am I overlooking something?

**Comment by phated** [comment]
Vinyl doesn't do any of those things.  Vinyl is very constrained to just be a representation of a file in memory.  Adapters are in control of generating Vinyl objects and interacting with a filesystem or some other medium.  If an adapter were to deal with deletion, it would just be a glorified globber and it doesn't fit the paradigm.  Anyway, this issue doesn't belong on Vinyl.
