### ISSUE TITLE
How do I use mocking to make this a drop in replacement for all FS calls?

### ISSUE THREAD

**Issue by megamindbrian** [gulpjs/vinyl#134]
I've started working on this:

https://github.com/webpack/memory-fs/issues/43

My goal is to be able to build packages/projects out of memory where just the node_module used are temporary stored in memory.  Kind of like webpack does but for the rest of the build chain as well.

**Comment by phated** [comment]
You can't and that's not a goal of this library. I think someone at the yeoman or bower team built what you are looking for on top of vinyl.
