### ISSUE TITLE
Cloned stream file content is not drained

### ISSUE THREAD

**Issue by sergeche** [gulpjs/vinyl#55]
Steps to reproduce:

1. Create file large enough to exceed `highWatermark` for file streams. In my case it’s 131KB file.
2. This code works fine:

```js
var vfs = require('vinyl-fs');

vfs.src('./large-file.txt', {buffer: false})
.pipe(vfs.dest('./dest'))
.on('end', function() {
	console.log('done!');
});
```

but this doesn’t, there’s no `done!` message and file isn’t written:

```js
var vfs = require('vinyl-fs');
var through = require('through2');

vfs.src('./large-file.txt', {buffer: false})
.pipe(through.obj(function(file, enc, next) {
	next(null, file.clone());
}))
.pipe(vfs.dest('./dest'))
.on('end', function() {
	console.log('done!');
});
```

Tested on node v0.10.38 and iojs v.2.3.1

After debugging, I found out that file contents reading stops after second 64KB chunk, looks like writing stream is not able to properly drain and resume reading. 

Playing with `File.clone()`, I’ve commented this line https://github.com/wearefractal/vinyl/blob/master/index.js#L68 and this test case worked fine.

Do you know if there are side-effects of this solution?

**Comment by contra** [comment]
@sergeche That line seems extraneous, want to send a PR to remove it?

**Comment by sergeche** [comment]
I will, but first I have to do more tests. I think the *right* solution might be much more complex. E.g. if I create two clones that attached to a single file read stream and read contents for one of them, will second clone restart read stream when I read from it?

**Comment by snowyu** [comment]
The simplest effective way is `createReadStream` agagin: https://github.com/snowyu/abstract-file.js/blob/master/src/attributes.coffee#L55

Even `PassThrough`, the data would be lost if one `through` stream is not ready to recevie data opportunely.

```coffee
contents = fs.createReadStream './README.md'
stream1 = contents.pipe(new stream.PassThrough())
stream2 = contents.pipe(new stream.PassThrough())

stream1.on 'data', (data)->console.log 's1', data.toString()
stream1.on 'end', ->
  # stream2 can not receive any data here.
  stream2.on 'data', (data)->console.log 's2', data.toString()
```

**Comment by sergeche** [comment]
I did some research on this problem.

Looks like the problem is during clone routine you end up with two consumers (original and cloned files) attached to a single reader. When you start reading from one of these streams, the other stream also receives data. But since that other stream is still in paused mode, it puts on pause the reader.

The quick and pretty valid solution, as @snowyu noted, is to create a new reader stream for a cloned file. The downside of this solution is that you’ll loose all piped streams from original file.

**Comment by phated** [comment]
@sergeche We don't want to lose all the piped streams.  What else can be done here?

**Comment by sergeche** [comment]
@phated I think the only solution is to clone all piped streams and arrange them into a new pipeline. And the only solution to do so properly is to get access to stream constructor.

I looked over repo issues and didn’t found any reports like this. Looks like there’s not so much users who need to use streams for file reading :) So I guess simply creating a new file stream reader will be OK.

**Comment by mcollina** [comment]
This example https://github.com/gulpjs/vinyl/issues/55#issuecomment-124931105 works fine node v4 and v5, but not on v0.10 and v0.12.

**Comment by phated** [comment]
@mcollina thanks, the example in the original issue works in node v5 also.  I kept the technical, stream-specific discussion in the readable-stream issue.

**Comment by phated** [comment]
It looks like this will be fixable on node 0.10 and 0.12 with some caveats and fully fixable on node 4/5/6.  I'll add more information here as I solidify it.

**Comment by phated** [comment]
This problem seems to be due to Streams2 implementation and is fixed with Streams3.  If you upgrade to node v4 or v5, the sample from the initial issue works perfectly.

**Comment by tunnckoCore** [comment]
@sergeche your second example from first post perfectly works in 0.10 for me. It emits `end` and file isn't corrupted (it is the same as the input file).
