### ISSUE TITLE
Great Thanks and Proposal

### ISSUE THREAD

**Issue by snowyu** [gulpjs/vinyl#56]
I  very love the KISS of Gulp 4.  I am too lazy to re-invent the wheel. But I have not reused the codes of vinyl when I'm making a project base on Gulp 4. So I had to create the [abstract-file](https://github.com/snowyu/abstract-file.js).
I am tired to type useless/unreadable punctuation(eg, braces), so I use coffee-script too.

* abstract [property-manager](https://github.com/snowyu/property-manager.js) to manage the file attributes.
* abstract the load(stats, contents) supports
* abstract folder/directory supports: It's the array of file object and [read-dir-stream](https://github.com/snowyu/read-dir-stream.js)
* abstract [path.js](https://github.com/snowyu/path.js)
* abstract fs: It should apply via `AbstractFile.fs = fs`
* abstract cwd: It should apply via `fs.cwd = process.cwd`

The usage of abstract-file is here: https://github.com/snowyu/custom-file.js

I hope we can work together, if you do not hate coffee-script.
Anyway, great thanks.

**Comment by contra** [comment]
Nope, I love coffee-script but not for any open source work. All of our open source code is in lowest common denominator JS to encourage more contributions

**Comment by phated** [comment]
Going to close this, as there are nothing actionable to address.
