### ISSUE TITLE
[question] vinyl virtual adapter

### ISSUE THREAD

**Issue by tmcw** [gulpjs/vinyl#69]
Admittedly a question: is there a module that works with vinyl that would allow piping files from a stream of vinyl objects into a virtual filesystem? I'm working on a [live reloading server](https://github.com/documentationjs/dev-documentation) for which it'd be useful to never save the results of a stream to disk, but to keep them in memory so that they can be served over HTTP.

**Comment by phated** [comment]
I think the closest thing to this would be https://www.npmjs.com/package/gulp-cached but it isn't really the same thing.  I've often thought about a similar thing to what you are building so that's pretty awesome.  I'm wondering if this has any tie-in to https://github.com/gulpjs/gulp/issues/357

**Comment by jskrzypek** [comment]
I believe this is what [`mem-fs`](https://github.com/sboudrias/mem-fs) does, but I'm not 100%. 

Looks like it uses a pretty old version of vinyl though...

**Comment by tmcw** [comment]
So far I'm working on a [very minimal server](https://github.com/documentationjs/documentation/blob/watch/lib/server.js) that keeps an array of files around - I'm not sure if it'll be enough, but it's working so far.

**Comment by Marak** [comment]
@tmcw - You might find some useful code in https://github.com/marak/vinyl-http

**Comment by contra** [comment]
Let me know when this is finished! This idea was actually what helped refine the concept of vinyl as a virtual file object

**Comment by tmcw** [comment]
I eventually wrote a very simple [memory-only server](https://github.com/documentationjs/documentation/blob/master/lib/server.js) that [I concat and set files on](https://github.com/documentationjs/documentation/blob/571137a77dfd8743ef209a40f7bea3d7f541e729/lib/commands/serve.js#L21). It works very well for this usecase.
