### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by tmcw** [gulpjs/vinyl#70]
I'm seeing some behavior changes between vinyl 0.5 and 1.0, and between vinyl-fs 1 and 2. Neither project has a changelog or release notes - could there be a little more information that lists what breaking changes occur?

**Comment by phated** [comment]
Yes, this needs to happen.  If you could go through the commit history and send us one of changes up until now, that would be insanely welcome.

**Comment by T1st3** [comment]
@phated @tmcw , I just forked the repo and added a changelog:
https://github.com/T1st3/vinyl/blob/master/CHANGELOG.md

Note that the changelog was created automatically with https://github.com/lalitkapoor/github-changes. 

if that file is OK for you, I may sure create a PR

**Comment by contra** [comment]
@T1st3 That looks nice, go ahead and send a PR

**Comment by phated** [comment]
Closed by #76
