### ISSUE TITLE
path.extname does not honor extensions with more than one dot

### ISSUE THREAD

**Issue by TimvdLippe** [gulpjs/vinyl#71]
path.extname of `foo.min.css` becomes `.css` instead of the expected `.min.css`

I use https://github.com/MaKleSoft/gulp-style-modules where I had to use the following configuration to make it work:

```js
.pipe(stylemod({
  filename: function(file) {
    var fixedPath = file.path.replace('.min', '');
    var extension = path.extname(file.path);
    return path.basename(fixedPath, extension) + "-styles";
  }
}))
```
with input `app/bower_components/fullcalendar/dist/fullcalendar.min.css`

**Comment by phated** [comment]
The extension is actually `.css` and is handled by node's built in parser.  I don't think we should change this.

**Comment by TimvdLippe** [comment]
Is it possible to add a second argument to `extname` to strip off everything past the first dot instead of the last dot?

**Comment by phated** [comment]
No, this is a setter/getter property, not a method you call.

**Comment by TimvdLippe** [comment]
Hm that's a pity, I will continue looking for other fixes then. Thank you for your time.
