### ISSUE TITLE
isSymlink property

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl#79]
In vinyl-fs, we look at a `symlink` property that doesn't seem to be part of vinyl at all, so I guess we just attach it in vinyl-fs.  I think this should be bubbled up to vinyl and we could add a `isSymlink` or `isSymbolic` method like `isNull`, etc.

@contra thoughts?

**Comment by contra** [comment]
isSymbolic makes the most sense, and I agree we should have this
