### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl#85]
In https://github.com/nodejs/readable-stream/issues/202, @mcollina brought up the fact that we might have memory leaks when a Vinyl object with streaming content is cloned.  The suggested solution was to delay creation until the streams were needed.

I'm opening this issue so we can discuss further.

**Comment by phated** [comment]
I'm not sure if this is similar in concept, but we are using `lazystream` when constructing Vinyl objects in vinyl-fs's `.src()` method (https://github.com/gulpjs/vinyl-fs/blob/master/lib/src/get-contents/stream-file.js#L15-L17)

**Comment by mcollina** [comment]
Oh, I didn't know `lazystream` even existed. You want something slightly different, you want a `lazystream` that can be cloned and passed around. This it's either a PR there or a new module.
I'll see if I can do a prototype of this.

**Comment by mcollina** [comment]
Here is my take on this issue: https://github.com/mcollina/cloneable-readable.
Please give it a spin, if it helps I need to do one more thing or two regarding error handling.

**Comment by phated** [comment]
@mcollina super cool!  I'll give it a try soon.
